// packages/synth-react/src/components/list/list.tsx
import React, { useEffect, useState } from 'react';
import { configRow } from 'synth-core/dist/utils';
import { FieldsConfig, Row } from 'synth-core/dist/models/list';
import { SynthList, SynthTitle } from '../../components';

function SynthReactList({
    loading,
    title,
    data,
    limit,
    activeKpi,
    fieldsConfig,
    decimals,
    expandable,
    enableDownload
}: Props) {
    const [ parsedData, setParsedData ] = useState([] as Row[]);

    useEffect(() => {
        if (fieldsConfig && data) {
            setParsedData(data.map((row) => configRow(row, fieldsConfig)));
        }
    }, [ data, fieldsConfig ]);

    return (
        <div>
            <SynthTitle titleText={title} />
            <SynthList
                loading={loading}
                data={parsedData}
                filterFields={activeKpi && [ activeKpi ]}
                defaultSortField={activeKpi}
                decimals={decimals}
                expandable={expandable}
                limit={limit}
                enableDownload={enableDownload}
            />
        </div>
    );
}

interface Props {
    loading?: boolean;
    title?: string;
    data?: Row[];
    limit?: number;
    fieldsConfig: FieldsConfig[];
    activeKpi?: string;
    decimals?: boolean;
    expandable?: boolean;
    enableDownload?: boolean;
}

SynthReactList.defaultProps = {
    loading: true,
    title: '',
    data: [],
    limit: undefined,
    activeKpi: undefined,
    fieldsConfig: [],
    decimals: true,
    expandable: false,
    enableDownload: false
} as Props;

export default SynthReactList;

// packages/synth-angular/src/components/list/list.component.ts
import { Component, Input, OnChanges } from '@angular/core';
import { FieldsConfig, Row } from 'synth-core/dist/models/list';
import { configRow } from 'synth-core/dist/utils';

@Component({
    selector: 'synth-ng-list',
    templateUrl: './list.component.html',
    styleUrls: [ './list.component.scss' ],
})
export class ListComponent implements OnChanges {
    @Input() loading: boolean;
    @Input() title: string;
    @Input() data: any[];
    @Input() limit: number;
    @Input() fieldsConfig: FieldsConfig[];
    @Input() decimals: boolean;
    @Input() expandable: boolean;
    @Input() enableDownload: boolean;
    @Input() activeKpi: string;

    public parsedData: Row[] = [];

    ngOnChanges() {
        this._parseList();
    }

    private _parseList() {
        this.parsedData = this.data.map((row) => configRow(row, this.fieldsConfig));
    }
}

<synth-title [titleText]="title"></synth-title>
{{ hasData }}
<synth-list
    [loading]="loading"
    [data]="parsedData"
    [filterFields]="activeKpi && [activeKpi]"
    [defaultSortField]="activeKpi"
    [decimals]="decimals"
    [expandable]="expandable"
    [limit]="limit"
    [enableDownload]="enableDownload"
></synth-list>
