// packages/glyph-react/src/wrappers/chipsbar/chipsbar.tsx
import { FilterSelectEvent, FilterUpdateEvent, UIInterface } from 'glyph-core';

import React from 'react';
import { GlyphChipsbar } from '../../components';
import { useFiltersConfig } from '../../providers/filter-state';

function GlyphReactChipsbar({ uiInterface, locale, basePath }: GlyphReactChipsbarProps) {
    const { filtersConfig, selectFilter, updateFilter, clearFilter, clearAll } = useFiltersConfig();

    const handleSelectFilter = (event: CustomEvent<FilterSelectEvent>) => {
        selectFilter(event.detail);
    };

    const handleFilterUpdate = (event: CustomEvent<FilterUpdateEvent>) => {
        updateFilter(event.detail);
    };

    const handleFilterClear = (event: CustomEvent<string>) => {
        clearFilter(event.detail);
    };

    const handleClearAll = () => {
        clearAll();
    };

    return (
        <GlyphChipsbar
            basePath={basePath}
            interface={uiInterface}
            locale={locale}
            filtersConfig={filtersConfig}
            onFilterSelect={handleSelectFilter}
            onUpdateFilter={handleFilterUpdate}
            onFilterClear={handleFilterClear}
            onClearAll={handleClearAll}
        />
    );
}

export interface GlyphReactChipsbarProps {
    /** UI interface *modern* | *classic* */
    uiInterface: UIInterface;
    locale?: string;
    basePath?: string;
}

GlyphReactChipsbar.defaultProps = {
    uiInterface: 'classic',
} as GlyphReactChipsbarProps;

export default GlyphReactChipsbar;

// packages/glyph-angular/projects/glyph-angular/src/lib/components/chipsbar/chipsbar.component.ts
import { Component, Input } from '@angular/core';
import { FiltersConfig, FilterSelectEvent, FilterUpdateEvent, UIInterface } from 'glyph-core';
import { Observable } from 'rxjs';
import { FilterService } from '../../services';

@Component({
    selector: 'glyph-ng-chipsbar',
    templateUrl: './chipsbar.component.html',
})
export class ChipsbarComponent {
    /** Filters interface *MODERN* | *CLASSIC* */
    @Input() interface: UIInterface;

    /** @ignore Filters state */
    filtersConfig: Observable<FiltersConfig>;

    constructor(private _filterService: FilterService) {
        this.filtersConfig = _filterService.filtersConfig;
    }

    /** @ignore Filter selection event */
    onFilterSelect(event: CustomEvent<FilterSelectEvent>) {
        this._filterService.selectOption(event.detail);
    }

    /** @ignore Filter clear event */
    onFilterClear(event: CustomEvent<string>) {
        this._filterService.clearFilter(event.detail);
    }

    /** @ignore Filter update event */
    onFilterUpdate(event: CustomEvent<FilterUpdateEvent>) {
        this._filterService.update(event.detail);
    }

    /** @ignore Clear all filters event */
    onClearAll() {
        this._filterService.clearAllFilters();
    }
}

<glyph-chipsbar
    [filtersConfig]="filtersConfig | async"
    [interface]="interface"
    [basePath]="basePath"
    (filterSelect)="onFilterSelect($event)"
    (filterClear)="onFilterClear($event)"
    (updateFilter)="onFilterUpdate($event)"
    (clearAll)="onClearAll()"
></glyph-chipsbar>
