// packages/glyph-react/src/wrappers/chipsbar/chipsbar.tsx
import { actions, FilterSelectEvent, Store, UIInterface } from 'glyph-core';

import React from 'react';
import { useDispatch, useSelector } from 'react-redux';
import { GlyphChipsbar } from '../../components';

function GlyphReactChipsbar({ uiInterface }: GlyphReactChipsbarProps) {
    const dispatch = useDispatch();
    const filtersConfig = useSelector((state: Store) => state.filters.filtersConfig);

    const handleSelectFilter = (event: CustomEvent<FilterSelectEvent>) => {
        dispatch(actions.filters.selectOption(event.detail));
    };

    const handleFilterClear = (event: CustomEvent<string>) => {
        dispatch(actions.filters.clearFilter(event.detail));
    };

    const handleClearAll = () => {
        dispatch(actions.filters.clearAll());
    };

    return (
        <GlyphChipsbar
            interface={uiInterface}
            filtersConfig={filtersConfig}
            onFilterSelect={handleSelectFilter}
            onFilterClear={handleFilterClear}
            onClearAll={handleClearAll}
        />
    );
}

export interface GlyphReactChipsbarProps {
    /** UI interface *modern* | *classic* */
    uiInterface: UIInterface;
}

GlyphReactChipsbar.defaultProps = {
    uiInterface: 'classic',
} as GlyphReactChipsbarProps;

export default GlyphReactChipsbar;

// packages/glyph-angular/projects/glyph-angular/src/components/chipsbar/chipsbar.component.ts
import { Component, Input } from '@angular/core';
import { FiltersConfig, FilterSelectEvent, UIInterface } from 'glyph-core';
import { GlyphFilterService } from '../../services/services.module';

@Component({
    selector: 'glyph-ng-chipsbar',
    templateUrl: './chipsbar.component.html',
})
export class ChipsbarComponent {
    /** Filters interface *MODERN* | *CLASSIC* */
    @Input() interface: UIInterface;

    filtersConfig: FiltersConfig = {};

    constructor(private _filterService: GlyphFilterService) {}

    onFilterSelect(event: CustomEvent<FilterSelectEvent>) {
        this._filterService.selectOption(event.detail);
    }
}

<glyph-chipsbar 
    [filtersConfig]="filtersConfig" 
    [interface]="interface"
    (filterSelect)="onFilterSelect($event)"
></glyph-chipsbar>
