// packages/glyph-components/src/stories/helpers/decorators.tsx
import { html } from 'lit-html';

export const WithGlobalDecorator = ({ template, ctx, style = '' }) => {
    const {
        globals: { locale, theme, fontSize },
    } = ctx;

    const bodyElementFirst = document.getElementsByTagName('body')[0];
    const bodyElement = parent.document.getElementsByTagName('body')[0];
    bodyElementFirst.className = theme;
    bodyElement.className = theme;

    if (fontSize !== 'base') {
        style = `${style}; --gui-font--base: ${fontSize}`;
    }

    return html`<div lang="${locale}" style="${style}">${template}</div>`;
};

// packages/glyph-react/src/helpers/decorators.tsx
import React, { useEffect } from 'react';
import { useDispatch } from 'react-redux';
import FilterStateProvider from '../providers/filter-state';
import { FiltersConfig } from './configs';
import { FilterEntities } from './filters';
import { actions } from 'glyph-core';

export const InitializeFilters = (Story: any) => {
    const dispatch = useDispatch();

    useEffect(() => {
        async function loadFilters() {
            dispatch(actions.filters.initialize(FilterEntities, 'test', FiltersConfig, {}));
        }
        loadFilters();
    }, [ dispatch ]);

    return <Story />;
};

export const WithFilters = (Story: any) => {
    return (
        <FilterStateProvider>
            <Story />
        </FilterStateProvider>
    );
};

export const WithCustomHeight = (height: number) => (Story: any) => {
    return (
        <div style={{ height }}>
            <Story />
        </div>
    );
};

export const WithCustomGlobals = (Story: any, context: any) => {
    const { theme, locale, fontSize } = context.globals;
    const bodyElementFirst = document.getElementsByTagName('body')[0];
    const bodyElement = parent.document.getElementsByTagName('body')[0];
    bodyElementFirst.className = theme;
    bodyElement.className = theme;

    return (
        <div className={theme} lang={locale} style={{ '--gui-font--base': fontSize } as any}>
            <Story {...context} />
        </div>
    );
};

export const WithGlobalTheme = (_: any, context: any) => {
    const { theme } = context.globals;
    const bodyElementFirst = document.getElementsByTagName('body')[0];
    const bodyElement = parent.document.getElementsByTagName('body')[0];
    bodyElementFirst.className = theme;
    bodyElement.className = theme;

    return ' ';
};
